### ISSUE TITLE
La Arquitectura que me funcionó en Vue

### ISSUE THREAD

**Issue by ederng** [eventloop/platicas#101]
### Sumario

La Arquitectura que he adoptado para trabajar en Vue después de haber fallado muchas veces en el intento. (Puede ser adaptable para component-based frameworks)

### Outline

1. Componentes
  - Componentes, no navajas suizas
  - Regla de oro de los componentes
  -  Estados de componentes
 -   No todo es un componente
2. Páginas como modelos
  - Usar el VM
  - Una págoina como proveedor de datos
3. Código Modular (Divide y vencéras, en serio, muy en serio)
  - ¿Por qué funciona el código modular?

Hola, escribí este artículo en Platzi, donde tengo ya las ideas aterrizadas sobre este tema: https://platzi.com/vuejs-profesional/tutoriales/mi-arquitectura-en-vue/

Presentar en ¿Octubre / Noviembre?

```yaml
name: Eder Negrete
url: https://twitter.com/ederyairr
pic: http://ederng.github.io/public/images/avatar.jpg
bio: "Young scrappy and hungry Frontend Developer"
```
