### ISSUE TITLE
Jest unit testing para fontend [reactjs] y backend [expressjs]

### ISSUE THREAD

**Issue by xalakox** [eventloop/platicas#102]
### Sumario

Hablaré sobre Jest, unit testing de reactjs en front y UT en backend

### Outline

- Acerca de mi y DLR
- Introducción a Jest y Coverage
- Creación de componentes con y sin enzyme
- Emulación de Eventos
- Snapshots y evaluación
- Backend Mockup usando nock
- Implementación en Backend de Jest 

```yaml
name: Salvador Aceves
url: http://salvador.aceves.mx
pic: https://aboutme.imgix.net/background/users/s/a/l/salvadoraceves_1498086082_393.jpg
bio: "Dev, tecnócrata y músico frustrado"
```
