### ISSUE TITLE
Async...Await

### ISSUE THREAD

**Issue by oscaroceguera** [eventloop/platicas#103]
### Título

Async...Await

### Sumario

Hablaré sobre el uso de funciones asíncronas (async/await).

### Outline

- Que es async...await
- Como funcionan
- Manejo de errores
- Loops
- Algunos ejemplos

```yaml
name: Oscar Eduardo Oceguera Bibriesca
url: https://oscaroceguera.github.io
pic: https://avatars2.githubusercontent.com/u/5040939?s=460&v=4
bio: "Desarrollador web, melómano de corazón y no me gusto polymer"
```
