### ISSUE TITLE
Aplicaciones Web Progresivas con Angular 5

### ISSUE THREAD

**Issue by jorge-indigo** [eventloop/platicas#105]
### Justificación

Hace un mes terminé el desarrollo de un CMS para la SEP de Sinaloa pero el frontend debía funcionar sin internet, además de ser rápido, etc etc. La aplicación ya se encontraba en un 70% de desarrollo sobre Angular 5 y fue un infierno encontrar la forma correcta de integrar PWA

### Sumario

Hablaré sobre integrar PWA con aplicaciones existentes en Angular 5.

### Outline

1. ¿Qué es PWA? (Ventajas y desventajas, comparaciones con apps nativas e híbridas)
2. ¿Cómo funciona? (Manifest, Service Workers)
3. Integrando PWA a un proyecto existente (Demo)

```yaml
name: Jorge Eduardo Ramón
url: https://twitter.com/Jorge_Rockr
pic: https://pbs.twimg.com/media/DTTPsbWUMAEPQYk.jpg
bio: "Amante de Node.js y de la pizza"
```
