### ISSUE TITLE
Tooling y Marble seeds

### ISSUE THREAD

**Issue by Siedrix** [eventloop/platicas#106]
### Summary

En CommonSense hemos estado trabajando en un repo llamado [Marble Seeds](https://github.com/latteware/marble-seed)*Missing documentation* que utilizamos para empezar todos nuestros proyectos. Lo cual nos permite tener una base de código reusable entre todos los proyectos a la que vamos agregando más funcionalidades para poder hacer proyectos más robustos con menos esfuerzo y poder compartir buenas practicas entre todo el equipo.

### Outline

- Por que es importante crear tooling
- Como generar tooling
- Demo de Marble Seeds

```yaml
name: Daniel Zavala
url: https://twitter.com/siedrix
pic: https://scontent-dft4-2.xx.fbcdn.net/v/t31.0-8/1147751_650695004949880_1726802145_o.jpg?oh=8f979416487b3ef57dbfd511544e555a&oe=5AE54A9D
bio: "Such Wow... Much JS, beer and pizza"
```
