### ISSUE TITLE
¿Qué hay de nuevo en ECMAScript 2018?

### ISSUE THREAD

**Issue by FiliJS** [eventloop/platicas#107]
### Sumario

Hablaré sobre ECMAScript (general) y me centraré en presentar las novedades de ES2018.

### Outline

- Historia y evolución de JS
- Historia de ECMASCRIPT (ES2015, ES2016 ... )
- ES2018

```yaml
name: Fili Santillán
url: https://filisantillan.com/
pic: https://pbs.twimg.com/profile_images/778822260463276032/AgNOmR79_400x400.jpg
bio: "Frontend Developer, Speaker, Blogger, Geek, Lover of code"
```
