### ISSUE TITLE
Por que aprender a hacer pruebas unitarias me cambio la vida.

### ISSUE THREAD

**Issue by kuroganito** [eventloop/platicas#108]
### Sumario

Contare por que hacer pruebas cambio mi forma de ver y hacer codigo.
Dare una introduccion al framework de testing que uso actualmente: Jasmine.
Quiero enfocarme en el tema de Spy para probar funciones con llamadas servidor.

### Outline

1. Presentacion
  - Quien soy y que hago
  - Por que no me gustaban las pruebas.
  - Por que termine amandolas.
2. Jasmine
  - Que es Jasmine y como funciona.
  - Lo basico: Describe It y Expect 
  - Un poco mas avanzado: Spy's
3. Dudas :)

```yaml
name: Oscar Alberto Paredes Garduño
url: https://twitter.com/kuroganito
pic: https://avatars1.githubusercontent.com/u/6679487?s=460&v=4
bio: "Una laptop, una bici e internet. Todo lo que necesito para vivir"
```
