### ISSUE TITLE
Leaflet para artistas

### ISSUE THREAD

**Issue by amaurs** [eventloop/platicas#109]
### Sumario

Leaflet es una herramienta open source para crear mapas interactivos. ¿Qué nos puede ofrecer el motor el motor de leaflet detrás cuando nos podemos ingeniosos? En esta platica mostramos tres ejemplos prácticos que se pueden hacer sin mucho esfuerzo.

### Outline

1. Como funciona el motor de baldosas de leaflet.
  - Por qué las proyecciones geográficas.
  - Como se ennumeran las baldosas del mapa.
2. Estructura de clases de leaflet.
  - Puntos para extender el código.
3. Ejemplos
  - Imagen estática navegable. (Proyección a coordenadas de la imagen)
  - Usar el motor para desplegar gifs animados. (Basado en el ejemplo de la documentación)
  - Consumir un Web Map Service para hacer zoom en el conjunto de Mandelbrot (¡Fractales!).

```yaml
name: Amaury Gutiérrez
url: https://twitter.com/amaurs
pic: https://pbs.twimg.com/profile_images/582810159065362432/E_sNdHEF_400x400.jpg
bio: Me gusta hacer cosas bonitas que no sirven para nada.
```
