### ISSUE TITLE
require.context

### ISSUE THREAD

**Issue by Sparragus** [eventloop/platicas#111]
### Sumario
Quiero dar una plática de `require.context`, un api sobre `require` que solo Webpack ofrece.

### Outline
_pending_

### Adword

```yaml
name: Richard B. Kaufman-López
url: https://twitter.com/sparragus
pic: http://kickass.partners/img/team/06.png
bio: "Ingeniero de frontend. Me gustan los pugs."
```
