### ISSUE TITLE
Entre JavaScripts y Machine Learnings

### ISSUE THREAD

**Issue by alexisllamas** [eventloop/platicas#112]
### Sumario

Esta plática es para platicarles un pequeño experimento que hice, una red neuronal en vanilla JavaScript. 

### Outline

1. Red neuronal 101
  - La definición pero sin palabras difíciles o matemáticas
2. ¿Qué vamos a construir?
  - Explicar lo qué hice
  - Cómo funciona y lo que va a hacer
3. Mi experencia
  - Cómo logré que funcionara
  - Retos
  - Mostrar código
4. ¿Qué aprendí?
  - ¿Es víable?
  - ¿Tiene futuro?
  - ¿Qué sigue?
  - ¿Cómo empezar en machine learning si no soy un genio?

```yaml
name: Alexis Navarro
url: https://twitter.com/AlexisMeLlamo
pic: https://pbs.twimg.com/profile_images/814145614799716353/LRVD1yZf_400x400.jpg
bio: "Una chela, una lap y mis ideas es todo lo que necesito"
```
