### ISSUE TITLE
WebAssembly

### ISSUE THREAD

**Issue by hiphoox** [eventloop/platicas#113]
### Sumario

El objetivo es platicar sobre el pasado, presente y futuro de WebAssembly. 
Esta charla estará basada en una conferencia que dieron dos de los fundadores de WebAssembly en Amsterdam este año.

Explicaremos exactamente que es WebAssembly y el impacto que tendrá no sólo para el Web sino
para el desarrollo en general.

### Outline

1. Importancia de la conferencia Curry-On
  - Objetivo de la conferencia
  - Quienes fueron los expositores
2. Explicación de WebAssembly
  - Pasado
  - Presente
  - Futuro
3. Conclusiones

```yaml
name: Norberto Ortigoza Márquez
url: https://twitter.com/hiphoox
pic: http://www.erlang-factory.com/static/upload/media/1438866456449138norbertoortigoza.jpg
bio: "Norberto es un desarrollador e instructor con más de 23 años de experiencia utilizando una gran variedad de lenguajes, entre ellos Smalltalk, Objective-C, Java, Javascript, C, C#, Python, Ruby, Go, Swift y Elixir. Ha dado cursos en Europa, USA, India y México. Ha sido instructor para Bignerdranch y Hipbyte. Es líder de desarrollo en Bunsan y de la comunidad Elixir Mexico City"
```
