### ISSUE TITLE
Crear dapps usando web3.js/solidity en Ethereum Blockchain

### ISSUE THREAD

**Issue by indie-rok** [eventloop/platicas#114]
<!--
// Puedes borrar este comentario sin broncas, pero antes de hacerlo lee
// y completa las instrucciones!

Presentar una plática en Eventloop es bien fácil:

1. El **título** de este issue debe ser el título de tu charla,
2. Un breve sumario (par de oraciones) que describan de que se trata
3. El outline que seguirás,
4. Tu "adword", y opcionalmente
4. Cuándo te gustaría presentar

### Sumario

Blockchain es una tecnología que esta revolucionando la forma en como compartir y analizar información. Primero, entenderemos que es blockchain y en que casos se necesita.

Despues, estudiaremos como usar la librería web3.js para crear una capa front end que consuma cualquier Smart Contract creado en Ethereum e interactuar con su blockchain.

### Outline

1. WTF is blockchain
  - Idea conceptual básica
  - Bitcoin vs Ethereum
  - Smart Contracts
2. Creando un Smart Contract en Ethereum
  - Usando Solidity
  - Remix como IDE
  - Haciendo deploy del Smart Contract en el blockchain.
3. Consumiendo ese Smart Contract con Web3.js y Metamask
  - WTF is metamask
  - Las transacciones en Ethereum cuestan dinero
  - Web3.js
  - Usando el contrato con Web3.js

```yaml
name: Emmanuel Orozco Colín
url: https://twitter.com/indie-rok
pic: https://pbs.twimg.com/profile_images/783401116348276736/ZWzhXzuc_400x400.jpg
bio: "Ingeniero de Software en @crowdbotics. Me gusta aprender tecnologías nuevas y jugar futbol."
```

Me gustaría en septiebre de ser posible.

La charla es 80% práctica donde todos los que traigan PC van a poder subir su contrato a la blockchain y poder interacuar con el usando Web3.js
