### ISSUE TITLE
Creación de API REST con AWS y NodeJS

### ISSUE THREAD

**Issue by jalmarazg** [eventloop/platicas#115]
### Sumario

AWS es una plataforma de servicios en la nube que, a través del tiempo, se ha posicionado como líder indiscutible en cuanto a opciones de escalabilidad y crecimiento.

En esta platica, mostrare una pequeña API funcionando con los servicios AWS API Gateway y AWS Lambda con código realizado en NodeJS. 

### Outline

1. AWS
  - ¿Que es AWS?
  - AWS API Gateway y Lambda en acción
  - ¿Por que elegir esta solución?
2. ¿Como se construyó?
- Mostrar como esta configurada la solución dentro de AWS
  - API Gateway: Seguridad, métodos y limites de API
  - AWS Lambda: Tiempo de ejecución de las funciones y variables de entorno
3. Funcionamiento 
 - Demostración del funcionamiento de la API usando Postman Client
4. Dudas

```yaml
name: José Roberto Almaraz González
url: https://twitter.com/ailesdenuit
pic: https://avatars1.githubusercontent.com/u/9245962?s=400&u=1386fe69e5c5153829a0174d29f5d492e19dfde5&v=4
bio: "Frontend Developer, AWS Certified Developer Associate and Software Engineer Trainee at Wizeline"
```
