### ISSUE TITLE
Experiencias de mis primeros trabajos como programador

### ISSUE THREAD

**Issue by rolandoesc** [eventloop/platicas#117]
### Sumario

Quiero hablar de las experiencias que he tenido en mis primeros trabajos como programador, cómo llegué y qué hice para avanzar (herramientas y feedback).   

### Outline

1. Sobre mí
- Background
- Tiempo en programación
- Empleos que he tenido
2. ¿De Customer Support a Full Time Developer?
  - ¿Qué me faltaba?
  - ¿Qué herramientas tomé?
  - ¿Como materializar lo aprendido en práctica?
3. Clase de Sobrevivencia en tu primer mes de trabajo: 101
  - Técnicas
  - Herramientas
  - Consejos 

```yaml
name: Rolando Escalona
url: https://twitter.com/rolandoesc
pic: https://pbs.twimg.com/profile_images/953143630411321344/Gt_WGNJx_400x400.jpg
bio: "Front-End engineer researching new UX patterns for the Blockchain industry  🔨"
```
