### ISSUE TITLE
 jQuery en tiempos de React

### ISSUE THREAD

**Issue by marulango** [eventloop/platicas#118]
### jQuery en tiempos de React

Cómo la biblioteca(librería?) que alguna vez fué la forma más popular de incorporar JS en tu proyecto y que ahora es relativamente impopular fue la mejor opción para lanzar un proyecto que tenía en mente.

### Outline

1. Evaluando el proyecto
  - Final Fantasy XIV & Crafting
  - Mi muy, muy específico problema
  - noquieropagarservidoreslol 

2. Y por qué no usas React?
  - véase 1.3
  - Y entonces…qué voy a usar?

3. Hazlo público, chance a alguien le sirve
  - Hola, Reddit!
  - Colaboración :D
  - KTHXBAI

```yaml
name: Marcela _Maru_ Lango
url: https://twitter.com/marulango
pic: https://pbs.twimg.com/profile_images/783401116348276736/ZWzhXzuc_400x400.jpg
bio: "Abuela Jóven. Tengo un gato que es un patán. De todas formas lo amo."
```
