### ISSUE TITLE
Aproximación a vuex en una SPA

### ISSUE THREAD

**Issue by magentaFire** [eventloop/platicas#119]
### Acercándote a Vue.js

Una breve introducción a este framework y un vistazo a algunas de sus características más llamativas que te permitirán diseñar interfaces e interactividad de manera muy rápida 

### Outline:
1. ¿De qué trata Vue.js? y porqué me gusta

- Introducción a Vue.js
- Easy setup
- Fast & easy prototyping (template syntax)
- Single File Components
- Progressive framework!
- Vuex
- Vue CLI
- Gran comunidad para pedir ayuda

2. Conclusiones

```yaml
name: Dafne Magenta Luna Casanueva
url: https://twitter.com/Magenta_Fire
pic: https://pbs.twimg.com/profile_images/1042850117534015488/8k0g6lcv_400x400.jpg
bio: "Tabaco no, chelas sí. Amo el cyberpunk y terminator.... Y una vez soñé con Vladimir Putin ñ.ñ"
```
