### ISSUE TITLE
Haciendo un buen CV para aplicar a un nuevo trabajo

### ISSUE THREAD

**Issue by jmz7v** [eventloop/platicas#120]
### Sumario

El CV es tu carta de entrada a un nuevo trabajo, un buen CV puede ser un gran win para ese trabajo que quieres, un mal CV puede hacer que no tengas esa oportunidad aún si técnica y profesionalmente eras el apropiado para el trabajo.

### Outline

1. ¿Por qué es importante hacer un buen CV?
  - Te ayuda a avanzar más rápido en un proceso
  - Es tu carta de presentación con la empresa si no estás conectado con alguien
2. Fallas comunes
  - No poner lo que hiciste en las empresas en las que trabajaste
  - No poner el nombre de las empresas en las que trabajaste
  - No poner que tienes 0 de reputación `true story`
  - Corregir faltas de ortografía
3. Mejora tu CV actual
  - Es posible que debas re-acomodar tu CV para diferentes procesos
  - Poner lo más importante hasta arriba (última experiencia laboral)
  - Trata de que sean máximo 2 páginas

```yaml
name: Julio Montaño
url: https://jmz7v.com/blog
pic: https://jmz7v.com/about/oaxaca.jpg
bio: "Yo sólo quería hacerme una página web y terminé programando por el resto de mi vida"
```
