### ISSUE TITLE
why you should use Storybook in your ReactJs project?

### ISSUE THREAD

**Issue by ezegg** [eventloop/platicas#122]
Summary 
Storybook is a tool that integrates with your current react app and allows you to develop components in isolation without dependencies. There is a lot of advantages that I will show to you in this presentation and why is a good practice.

Outline

1. What is storybook?.
2. How i can use it? Is it possible to integrate it into my project?.
3. Real use case.
4. Advantages and disadvantages.
5. Final thoughts and conclusion.

```yaml
name: Ezequiel García
url: https://twitter.com/ezeezegg
pic: https://pbs.twimg.com/profile_images/953241026629652481/249OccUL.jpg
bio: "Hi, I'm Eze I love traveling, knowing the world and people. In my free time I'm Fullstack Developer in Follio, currently working with Reactjs 😍🙌"
```
