### ISSUE TITLE
Mi base de datos favorita es Google Spreadsheets

### ISSUE THREAD

**Issue by Sparragus** [eventloop/platicas#124]
### Sumario

Recientemente aprendí a amar Google Spreadsheets como base de datos. Resulta que una hoja de cálculos es una herramienta que me permite desarrollar prototipos y experimentos de forma rápida y simple.

En está plática presentaré como se puede usa GS para crear una tabla de contenido (algo así como [Contenful](https://www.contentful.com/)). La utilizaré para crear una landing page donde el contenido puede ser modificado en GS y se puede mandar a hacer deploy desde GS mismo.

### Outline

1. Presentar el problema: quiero hacer un prototipo con herramientas que me ayuden a ser flexibles y rápido.
2. Google Spreadsheets como DB
3. Funciones tipo lambda como mi API
4. Demo: Modificar el contenido de una landing page desde GS. Hacer deploy desde GS

### Sobre mi
```yaml
name: Richard B. Kaufman-López
url: https://twitter.com/sparragus
pic: https://i.imgur.com/HiUQkUy.png
bio: "Web engineer. JavaScript. Pugs."
```

### Me gustaría presentar en
Me encantaría ser la primera plática de Enero 2019
