### ISSUE TITLE
Hype_Cycle.js

### ISSUE THREAD

**Issue by elionaz** [eventloop/platicas#129]
### Sumario

La adopción de javascript ha crecido de manera exponencial en los últimos años, se han logrado muchas cosas aunque también faltan otras. Explicaré el crecimiento, la adopción y lo que podría pasar con JS y su relación con el “Hype Cycle” de Gatner.

### Outline

**1. ¿Qué es el Hype Cycle?**
   -    Gartner
   -    Technology Trigger (Disparo de la tecnología)
   -    Peak of Inflated Expectations (Pico de altas expectativas)
   -    Trough of Disillusionment (Cruce de la desilusión)
   -    Slope of Enlightenment (Pendiente de la ilustración)
   -    Plateau of Productivity (Meseta de Productividad)

**2. Ejemplos con tecnología (2018)**

**3. ¿Y esto qué tiene que ver con JS? (Relación con las fases del Hype Cycle)**
   -    Brendan Eich y los 10 días en 1995 (TT) 
   -    Librerías (TT)
   -    Frameworks (POIE)
   -    Detractores del JS (TOD)

**4. ¿Qué necesita JS?**

```yaml
name: Jonathan Contreras
url: http://elionaz.com/
pic: https://pbs.twimg.com/profile_images/992062471006539776/zgMhUPTX_400x400.jpg
bio: “Early Adopter de todo”
```
