### ISSUE TITLE
Análisis de precios diarios de combustibles con Python desde tu laptop

### ISSUE THREAD

**Issue by nerdzila** [eventloop/platicas#130]
### Sumario

O _Dónde venden gasolina más barata - The nerd way_

Cómo poder analizar con gráficas bonitas y claras los precios diarios e históricos de las gasolinas y diésel a nivel nacional con un simple script de Python y algo de curiosidad, desde tu laptop, pero con la información en la nube para compartirla con la banda.

### Outline

    1. Por qué precios de combustibles
    2. Qué es un ETL y por qué Python
    3. No necesitas un cluster de Kubernetes para esto, sólo tu laptop #Serverless
    4. Cómo correr el script y visualizar la información
    5. Sabrás dónde venden gasolina más barata en CDMX o Guamúchil :)

```yaml
name: Alfonso Sánchez
url: https://twitter.com/nerdzila
pic: https://pbs.twimg.com/profile_images/1281807268/Avatar-caricaturesco_400x400.jpg
bio: "Ex-programador exiliado en las tierras del análisis de datos y el aseguramiento de calidad"
```
