### ISSUE TITLE
Mesero, hay CSS en mi JavaScript

### ISSUE THREAD

**Issue by ricardoerl** [eventloop/platicas#132]
### Sumario
Nuevas metodologías y herramientas vienen a desafiar la forma en la que escribimos CSS para aplicaciones web, pero ¿por qué se crearon? ¿cuáles son sus ventajas y limitantes? ¿cómo lo puedo usar en mi día a día? ¿vale la pena aprenderlo? En la charla compartiré mi experiencia respondiendo a estas preguntas y demostraré con algunos ejemplos de código la manera en la que puedes comenzar a usar estas herramientas en tus proyectos.

### Outline
* Presentación
* Mi historia escribiendo CSS
* CSS en mi JavaScript (la novela)
* Herramientas para comenzar
* Consejos para seguir aprendiendo

```yaml
name: Ricardo Ramírez
url: https://twitter.com/ricardoerl
pic: https://pbs.twimg.com/profile_images/1080316785713307648/5jrSKPmr_400x400.jpg
bio: "Desarrollador frontend y coorganizador HorchataJS El Salvador"
```
### Me gustaría presentar en

Voy a estar en CDMX la primera semana de abril 2019 por lo que esos dias serian ideales.
