### ISSUE TITLE
Montessori para ser Agile 

### ISSUE THREAD

**Issue by AcheZeta** [eventloop/platicas#133]
### ¿Puede un metodo educativo hacernos buenos jefes, empleados y personas?

Hoy en día la filosofía educativa de María Montessori es utilizada en colegios de todo el mundo y se parece más a trabajar en google que a una escuela como a la que tal vez fuimos, 
A 112 años ¿Qué hemos aprendido de ella para ser mejores programadores, estudiantes o CEOs?

### Outline

1. Presentación:
  - ¿Quién fue María Montessori?
  - ¿Quien Soy y cómo llegué aquí?
2. Importancia de un espíritu autodidacta
  - Google, Amazon y Wikipedia
3. ¿Dudas?

```yaml
name: Hameyalli Elizalde
url: https://medium.com/@AcheZeta
pic: https://avatars2.githubusercontent.com/u/1633468?s=460&v=4
bio: "Joven e Impetuosa Padawan, laboratorian, siempre me equivoco"
```
Fecha tentativa: Abril / Mayo / Junio
