### ISSUE TITLE
Node.js Multi threading

### ISSUE THREAD

**Issue by jorgeramon** [eventloop/platicas#134]
### Sumario

Javascript es un lenguaje de un sólo hilo de ejecución, entonces... ¿por qué Node.js es tan eficiente en comparación con lenguajes Multi threading como Java, C# y PHP? Todo es gracias al modelo de concurrencia utilizando Event Loop.

¿Es posible hacer multi threading en Node.js? Sí! apartir de la versión 10.5 es posible.

### Outline

1. ¿Qué es Node.js?
2. ¿Cómo funciona y por qué es tan rápido? (Event loop)
3. Multi threading en Node.js (Workers)
4. Ejemplo: Implementación de setTimeout con Workers

```yaml
name: Jorge Ramón
url: https://twitter.com/Jorge_Rockr
pic: https://pbs.twimg.com/media/DTTPsbWUMAEPQYk.jpg
bio: "Amante de Javascript y de la pizza"
```
Fecha tentativa: Abril (excepto el 3 de Abril) / Mayo / Junio
