### ISSUE TITLE
Razonando Sobre ReasonML

### ISSUE THREAD

**Issue by AlxSavage** [eventloop/platicas#135]
### Sumario 🐙

ReasonML es el nuevo y atractivo vecino de JavaScript que está ganando popularidad y robándose la atención de muchos developers en el mundo Frontend.

Pero, ¿Por qué?

En esta plática voy a hacer una pequeña introducción a ReasonML y todas las cosas emocionantes que nos ofrece, así cómo algunos ejemplos de cómo llevar a Reason a nuestro mundo de componentes usando ReasonReact. Y, muchas razones más para tener una muy racional curiosidad sobre ReasonML.

--------

### Outline ✨

1.- Presentación
- Hola, soy Ale! (presentación)
- ¿De que se trata Reason?
2.- Comenzando con Reason
- La función de la Programación Funcional
- ¿Que es OCaml y con que se come?
3.- Reason y JavaScript
- ¿Y que vela tiene BuckleScript en todo esto?
- Ok, pero, ¿que tiene que ver JS?
4.- Jugando con Reason
- El hype de Reason
- Tipos de datos confiables
- Manejo de errores
5.- Librerías
- ReasonReact
- Reprocessing
5.- Conclusión
- ¿Cómo comienzo a usarlo ahora mismo?

--------

```yaml
name: Ale Villa
url: https://twitter.com/alxsavage
pic: https://instagram.fmex3-1.fna.fbcdn.net/vp/b4733fc1ff8f12edf17b0bd664566518/5D392DD9/t51.2885-15/e35/53095618_1206996422808951_1218183459415929457_n.jpg?_nc_ht=instagram.fmex3-1.fna.fbcdn.net
bio: "Nómada Digital & Frontend Software Engineer en Webflow"
```

--------

### ⏳ Cuándo te gustaría presentar?
Mayo 2019 🎉
