### ISSUE TITLE
Math4Devs (tips & tricks in JS)

### ISSUE THREAD

**Issue by soybisonte** [eventloop/platicas#136]
### Sumario

Saber matemáticas entre programadores es como tener super poderes, pero con un gran poder, viene una gran responsabilidad. 
En ésta charla podremos sobre la mesa algunos trucos sencillos para iniciarse en este gran universo, con ejemplos aplicados al Front End usando JS. Veremos un panorama general para que puedas comenzar a aprender de forma simple, como añadir esta gran herramienta a tu stack.

### Outline
1.- Intro
  - Soy Bisonte, presentación
  - ¿Por qué esta charla? Desmotivaciones.png 

2.- Por dónde comenzamos…
  -  ¿Qué es una función?
  -   Dominio e Imagen
  -  ¿Operadores, qué es eso?

3.- Interpolación, Trigonometría y Módulos
-   Interpolación
-   Funciones trigonométricas (seno, coseno y tangente)
-   Aritmética Modular

4.- Casco y fusca, tirando líneas de código
- Interpolación 
- Seno, Coseno y Tangente
- Módulo N

5.- Librerías
-  P5js
- THREE
- GSAP

6.- Recomendaciones

-   ¿Cómo aprender matemáticas solo y no morir en el intento?

```yaml
name: Heri Rodríguez A.K.A. Bisonte
url: https://www.soybisonte.com
pic: https://instagram.fntr4-1.fna.fbcdn.net/vp/a1ae41a72e618ab7e2b5b13565ceb11b/5D323A7C/t51.2885-15/e35/43035278_500879327055024_5912991048287661791_n.jpg?_nc_ht=instagram.fntr4-1.fna.fbcdn.net
bio: "Música, poesía y código, Creative Developer At BBVA Bancomer"
```
