### ISSUE TITLE
build a accessible components from scratch

### ISSUE THREAD

**Issue by yeion7** [eventloop/platicas#137]
### Sumario

Hablaré sobre como construir un componente que sea accesible, en este caso voy a construir un combobox

Voy a estar en mayo en CDMX, me gustaría darla en ese mes

### Outline

1. Construir un combobox en un tweet
2. Agregar propiedades aria
3. Agregar interacción con el teclado
4. Manejo del focus y live regions

No voy a hacer código en vivo, voy a ir entre problemas y mostrando código con code surfer

Mi idea de la charla es mostrar cada paso y problemas al implementar accesibilidad en un componente

```yaml
name: Yeison Daza
url: https://twitter.com/yeion7
pic: https://pbs.twimg.com/profile_images/861779454389104641/78fhClSX_400x400.jpg
bio: "papá de un montón de gatos"
```
