### ISSUE TITLE
Kue - Priority job queue with Node.js

### ISSUE THREAD

**Issue by lzamudio** [eventloop/platicas#139]
### Sumario

¿Cuántas veces no hemos tenido problemas de “cuellos de botella” en nuestras aplicaciones y bloquean a otros procesos? Con Kue podemos crear colas de trabajo y optimizar algunos procesos críticos en nuestra aplicación.

Les platicare de mi experiencia con Kue en un proyecto en producción además de puntos clave sobre su uso.

### Outline

1. Motivación: ¿Cómo y por qué llegue a este punto?
2. ¿Qué es una **_priority job queue_**?
3. Kue en acción (ejemplo)

```yaml
name: Luis Zamudio
url: https://twitter.com/luis_zamudioc
pic: https://pbs.twimg.com/profile_images/344513261583320613/500e71b441202892102232327d8ec18a_400x400.jpeg
bio: "Encuentra lo que amas y deja que te mate"
```
