### ISSUE TITLE
Creando tu primera aplicación Desktop multi-plataformas usando HTML, CSS, JavaScript y Electron

### ISSUE THREAD

**Issue by ricardoalcocer** [eventloop/platicas#140]
### Sumario

En esta plática aprenderás los aspectos más básicos de como crear tu primera aplicación Desktop utilizando tecnologías web.  Si sabes trabajar con tecnologías Web, ya sabes cómo crear aplicaciones de escritorio.

### Outline
  - Brevemente, mi historia y mi pasión por el cross-platform
  - Temas psicológicos sobre desarrollo cross-platform
  - Sobre Electron
      - Ejemplos de aplicaciones hechas en Electron
  - Crear un proyecto paso a paso
  - Al finalizar la plática, habrás entendido como estructurar tu primer proyecto, compilarlo para "development" y empacarlo como un app nativo para Mac.
    - Sólo puedo demostrar Mac, pero daré información y recursos como cómo hacer "deployment" para Windows y Linux
 - Hablaré de alternativas para hacer que tus aplicaciones de escritorio tengan el aspecto visual que tu usuario espera para la plataforma con la cual trabaja
 - Te compartiré muchos recursos que te ayudaran llevar tu desarrollo de aplicaciones de escritorio a un nivel profesional

```yaml
name: Ricardo (Alco) Alcocer
url: https://alco.rocks
pic: http://drops.ricardoalcocer.com/drops/1271259.jpeg
bio: "Educador, programador, emprendedor, hacker, guitarrista, mago.  Mi pasión es aprender y ayudar a otros."
```

Estaré explicando basado en este REPO: https://github.com/ricardoalcocer/electron_scaffolding
