### ISSUE TITLE
Cómo usar Step Functions para tu proyecto... y para todo en realidad.

### ISSUE THREAD

**Issue by ortimanu** [eventloop/platicas#141]
### Sumario

Como developer muy probablemente has tenido que diseñar y desarrollar máquinas de estado o programas que envuelven el procesamiento de data en distintos pasos o "steps". Esto se complica, cuando los pasos son muy distintos entre ellos, de tiempos variables o que dependen de distintos servicios no necesariamente interconectados. Hasta hace poco, habíamos tenido que desarrollar estos procesos en infraestructura monolítica la cual nos impedía el rápido desarrollo, era muy propicia a errores y ni hablar de hacerle cambios al proceso.

¡De suerte, hoy contamos con la herramienta de Amazon Web Services llamada AWS Step Functions! Esta herramienta "serverless" nos permite desarrollar estas subrutinas de flujo de trabajo mucho más eficientemente, permitiéndonos coordinar múltiples servicios, funcionalidades y lógicas de manera visual y con un orden claro y fácil de entender. Lo mejor de todo, gracias a su arquitectura serverless, es que son altamente modificables, son infinitamente escalables y su costo es extremadamente bajo.

En esta charla, te mostraré con ejemplos y situaciones prácticas (por las que probablemente todos hemos pasado) cómo programar, configurar y poner a correr flujos de trabajo utilizando AWS Step Functions.

### Outline

1. ¿Qué es una máquina de estado o un flujo de trabajo?
  - Breve teoría
  - Aplicaciones comunes
  - Beneficios
2. ¿Qué son las AWS Step Functions?
  - Breve descripción de uso y arquitectura.
  - Tipos de pasos y posibilidades.
  - Demostración sencilla de la consola AWS Step Functions?
 -  Cómo definir el diagrama y poner a correr el flujo.
 - Costos
3. Demo
  - Presentación de código en node.js y estructura serverless.
  - Demo de la máquina corriendo.
  - ¡Visualización de los pasos y sus resultados!

```yaml
name: Manuel Ortiz Bey
url: https://twitter.com/mortizbey
pic: https://pbs.twimg.com/profile_images/529654959973748737/KNENYM_W_400x400.jpeg
bio: "Además de ir a la playa y ver Netflix, soy un fan de la arquitectura de software y de perder el tiempo durante el día para entonces programar hasta tarde en la noche ;)."
```

### ⏳ Cuándo te gustaría presentar?
5 de junio 2019
