### ISSUE TITLE
Nestjs: un framework para aplicaciones del lado del servidor

### ISSUE THREAD

**Issue by HeberGB** [eventloop/platicas#142]
### Sumario

Nestjs es un framwork de Node muy influenciado por Angular, el cual sirve para construir aplicaciones del lado del servidor, que es bastante flexible, escalable y sobre todo es una tecnología que actualmente tiene una gran comunidad.

### Outline

1. Introducción
  - ¿Qué es Nestjs?
  - ¿Qué dependencias necesitas para empezar un proyecto?
2. Principales conceptos
  - Modules
  - Controllers
  - Providers
3. ¿Cómo hacer una API Rest?
  - Crear un module
  - Crear el controller
  - Crear el provider(service)
4. ¿Qué más puedo construir con Nestjs?
  - Auth
  - GraphQL
  - WebSockets
  - Microservices (Redis, RabbitMQ, gRPC)

```yaml
name: Heber Grajeda
url: https://twitter.com/HeberGB
pic: ![image](https://user-images.githubusercontent.com/18607092/59115291-98589380-890e-11e9-9f78-0db40501f0d1.png)

bio: "Aprendedor permanente, entusiasta de Node, fan de Docker y actualmente Full-stack Developer"
```
