### ISSUE TITLE
Service Workers

### ISSUE THREAD

**Issue by Sparragus** [eventloop/platicas#53]
Estamos buscando un ponente para que dé una plática de este tema.

Presentar una plática en ChelaJS es bien fácil. Necesitamos:
1. El título de tu charla,
2. Un breve sumario (par de oraciones) que describan de que se trata
3. El outline que seguirás,
4. Tu "adword", y opcionalmente
5. Cuándo te gustaría presentar

Si tienes dudas o te gustaría platicar antes de presentar:
- Échale un ojo al wiki: https://github.com/javascriptmx/chelajs/wiki
- Checa #chelajs en nuestro canal de slack: https://chat.javascriptmx.com

Usa el 'template' aqui abajo, cópialo, y envía la información como comentario a este issue.

---
### Título

Como dar pláticas en ChelaJS
### Sumario

Hablaré sobre...
### Outline
1. Presentar pláticas es la onda
   - Cuenta una historia
   - Hablanos sobre lo que aprendiste
   - Muestranos tus proyectos
2. Enemigos comunes
   - Código diminuto (36px pa arriba)
   - Demasiado texto (sólo bullets)
3. ¿Cómo le hacemos?
   - Dry runs
   - Estructurando nuestras ideas
   - ??
   - PROFIT!!!1!
### Short Bio/Adword

``` yaml
name: Graciela J. Script
url: https://twitter.com/chela_js
pic: https://pbs.twimg.com/profile_images/704544900990152704/r1XMV2Xv_400x400.jpg
bio: "Tu biografía en una oración"
```
### Cuando te gustaría presentar?

En el ChelaJS de julio 2016
