### ISSUE TITLE
Ciencia computacional para generar identidades de marca

### ISSUE THREAD

**Issue by marulango** [eventloop/platicas#61]
A.K.A. Branding generativo

Casos de estudio de cómo he estado utilizando Javascript para generar identidades de marca que no son tu jpeg plano promedio.
Osea, logos que están _vivos_

_Outline_
0. Auto-promoción sinverguenza & Anuncios parroquiales de WWCode
1. Qué es _branding generativo_ y con qué se come
2. ¿Cómo usas javascript para diseñar?
3. SUPER HAPPY DEMO TIME
4. Gracias & @marulango en las mejores redes sociales

_Fechas_
De preferencia entre septiembre/agosto works.
Si no, lo pueden poner cuando no tengan plática.

``` yaml
name: Marcela 'Maru' Lango
url: https://maruma.ru
pic: https://pbs.twimg.com/profile_images/445400536569749504/8vJ-Prbe.png
bio: Full Stack Designer, Pokémon Master, Señora Honoris Causa.
```
