### ISSUE TITLE
ML / Clasificación de Texto usando NodeJS

### ISSUE THREAD

**Issue by xalakox** [eventloop/platicas#63]
## Sumario

Hablaré sobre machine learning usando naturaljs y otras técnicas de clasificación bayesiana; intro a deep learning con Tensorflow.

### Outline

1. Tokenización de textos en español
2. Clasificación usando Bayesiana y Regresión Logísitca
3. Redes Neuronales y Tensorflow

Cada paso de la presentación tendrá un demo práctico; de hecho todo será en vivo, muy leve marco teórico y ejemplos al por mayor.

```yaml
name: Salvador Aceves
url: https://twitter.com/salvadoraceves
bio: "Viejo programador"
```
