### ISSUE TITLE
Estructura de folders de aplicaciones de React

### ISSUE THREAD

**Issue by Sparragus** [eventloop/platicas#68]
### Sumario

Una de las decisiones de diseño más importante que un ingeniero de software debe tomar es la estructura de folders de una aplicación. Una estructura bien diseñada es esencial para que un proyecto complejo pueda crecer.

En esta plática veremos como _yo_ estructuro mis aplicaciones de React. Paso a paso iremos viendo como ir organizando un proyecto que va creciendo. En el transcurso, discutiremos el _por qué_ de las decisiones y los _tradeoffs_ que estas implican.

Esta plática es dirigida a las personas han aprendido React haciendo tutoriales y pequeños proyectos y que quieren dar el paso de hacer aplicaciones más grandes con React.
### Outline

(Abierto a sugerencias)
1. Introducción
   - La gran mayoría de los tutoriales crean folder agrupando archivos con una funcionalidad parecida. (Actions, Components, Containers, Reducers, ...)
   - Qué pasa si mi aplicación crece y mantengo esta estructura.
   - Una alternativa: Organizando por feature vs organizando por funcionalidad.
2. Organizando por feature
   - Nuestra esctructura de folders es un espejo de nuestras rutas.
   - Cada ruta tiene una 'pantalla'.
   - Como organizar contenedores, components, pruebas.
   - Como varias pantallas pueden compartirse componentes.
3. Organizando Redux
   - Redux duck modules
4. Resumen
### Fecha

Noviembre 2016
### Adword

``` yaml
name: Richard B. Kaufman-López
url: https://twitter.com/sparragus
pic: https://avatars2.githubusercontent.com/u/80982?v=3&s=466
bio: "Ingeniero de software. De día, hacker en aliada.mx. De noche, hacker en el @ledhack, co-organizador de Eventloop, e invitado regular de @discomania_fm."
```
