### ISSUE TITLE
Aplicaciones de Node con Docker

### ISSUE THREAD

**Issue by luismendozamx** [eventloop/platicas#69]
### Sumario

La idea es hablar sobre cómo empaquetar una aplicación de Node, escrita con express y Mongoose en un contenedor de Docker con una base de datos de MongoDB también dentro de su propio contenedor. Las herramientas principales que se expondrían serían el `Dockerfile` y `docker-compose`. Al final me gustaría cerrar con una breve explicación de cómo hacer deploy de una solución basada en contenedores y una lista de las posibilidades (Kubernetes, Docker Swarm y DCOS).
### Outline
1. Intro a Docker
2. ¿Por qué contenedores?
3. Dockerfile
4. `docker build & docker run`
5. `docker-compose`
6. Ejecución de tests dentro del contenedor.
7. ¿Cómo diablos pongo esto en producción?

``` yaml
name: Luis Mendoza
url: https://twitter.com/luismendozamx
pic: https://pbs.twimg.com/profile_images/586204902705070082/fAMvbOKD_400x400.jpg
bio: "Full-stack Developer / Technical Lead @ GBM Digital. A veces tomo fotos."
```
