### ISSUE TITLE
Programación funcional

### ISSUE THREAD

**Issue by Ikana** [eventloop/platicas#70]
### Sumario

En los últimos años con la introducción de sistemas compuestos de cientos, si no es que miles de componentes diferentes, los paradigmas de programación que dependen de tener un estado mutable, se quedan cortos.

En esta platica discutiré un poco sobre la historia de la programación funcional , conceptos básicos  para javascript y un ejemplo de como yo aplico este paradigma en un proyecto de react real.

### Outline

1. Historia (Heráclito, calculo lambda)
2. Lenguajes funcionales (excel, lisp, Haskell y javascript)
3. Funciones de alto nivel en javascript (map, reducer, filter)
4. Componentes de alto de niver en react

```yaml
name: Rodrigo Quezada
url: https://twitter.com/rodikana
pic: https://en.gravatar.com/userimage/21615064/2a04478fb27406fbb324899e8a8a4bc3.jpg?size=200
bio: "Front-end developer en holagus"
```
