### ISSUE TITLE
Cómo usar "linting" para mejorar la calidad de tu código

### ISSUE THREAD

**Issue by a2ndrade** [eventloop/platicas#71]
### Summary

"Linting" es un tipo de análisis estático que asegura que el código sea escrito con cierto estilo y siguiendo ciertas reglas. Esas reglas pueden ser "best practices", definidas por la comunidad, o reglas creadas específicamente para tu aplicación.

En esta plática hablaremos de ESLint, una de las librerías más populares y flexibles. Veremos cómo se usa, cómo se configuran reglas existentes y mostraremos cómo crear nuevas reglas para una aplicación en React. Todo el código del demo estará disponible en github.

Para crear nuevas reglas, hablaremos de que es un árbol de sintaxis (parse tree) y lo utilizaremos para escribir código que analize la estructura del código de nuestra aplicación. Por último, explicaremos cómo registrar estas nuevas reglas localmente y como publicarlas para ser accedidas públicamente y/o ser reutilizadas por múltiples aplicaciones.

### Outline

1. Que es "Linting"?
2. Porque ESLint?
3. Instalación e uso
4. Configuración
5. Reglas
6. Árboles de sintaxis
7. Cómo crear nuevas reglas
8. Cómo registrar nuevas reglas localmente
9. Cómo publicar nuevas reglas
10. Otros ejemplos de reglas

### About me
```yaml
name: Antonio andrade
url: https://twitter.com/a2ndrade
pic: https://pbs.twimg.com/profile_images/696054017391140865/WLG6GGgO.jpg
bio: Software Architect @ appian.com
```
