### ISSUE TITLE
Swagger

### ISSUE THREAD

**Issue by xalakox** [eventloop/platicas#72]
**swagger.io**

### Sumario
Usando swagger en el desarrollo de APIs, un caso práctico.

### Outline

- Intro a Swagger
- Que resuelve Swagger
- Con que es compatible
- Caso Práctico

Podría presentarlo en el 2016? pero no entre el 15 dic y 3 de enero

```yaml
name: Salvador Aceves
url: https://twitter.com/salvadoraceves
pic: https://pbs.twimg.com/profile_images/799281217828884480/8hIKG10H.jpg
bio: "Developer, entrepreneur, occasional guitar player; but most importantly family father."
```
