### ISSUE TITLE
Draft.js – cómo crear tu propio editor de texto.

### ISSUE THREAD

**Issue by jeduan** [eventloop/platicas#73]
Quiero hablar sobre cómo cree un editor de comentarios usando [draft.js](http://draftjs.org) y un feature de menciones que se ve muy seguido en lugares como Facebook y Dropbox.

### Outline

1. El mundo mágico de textarea
1. Lo horrible que es `[contenteditable]`
1. Principios de diseño de draft.js
1. Capturar el texto que el usuario escribe
1. Bloques de texto estructurado FTW.
1. Toques finales

```yaml
name: Jeduan Cornejo
url: https://twitter.com/jeduan
pic: https://pbs.twimg.com/profile_images/791128400115163136/LeIzW8qc.jpg
bio: "Una vez empecé a organizar un evento de JavaScript."
```
