### ISSUE TITLE
Angular 2: Componentes fantásticos y donde programarlos. 

### ISSUE THREAD

**Issue by kiramishima** [eventloop/platicas#74]
Hablaré sobre Angular 2 por que todo mundo habla de React y no de la nueva versión de Angular desde que salio un release, de como iniciar y usar las herramientas de Angular 2 para hacer una aplicación en 2 días sin tener conocimiento de Frontend, así de algunos recursos que les pueden ayudar a comenzar.

### Outline

1. El mágico mundo de Angular 2.
2. Un framework fantástico con cosas extrañas
    * Components
    * Routes
    * Services
    * Pipes
3. The Angular 2 Bro Code (Styleguide + tslint = FTW)
4. Angular CLI FTW
5. Toques Finales

```yaml
name: Paul Arizpe
url: https://twitter.com/kiramishima
pic: https://avatars3.githubusercontent.com/u/12620426?v=3&s=460
bio: "El que cambia backends hechos en Java a NodeJS ó Go/F#"
```
