### ISSUE TITLE
Antipatrones en JavaScript: cosas que nunca debes hacer

### ISSUE THREAD

**Issue by enrique7mc** [eventloop/platicas#75]
### Sumario

Aprender qué es lo que **no** se debe hacer es, en muchos casos, más difícil que aprender lo que sí se debe hacer.

En esta presentación vamos a explorar ejemplos muy comunes de antipatrones en JavaScript y cómo solucionarlos, lo que nos permitirá crear software de mejor calidad y evitar avergonzarnos frente a nuestros colegas por escribir mal código.

### Outline

1. Qué es un antipatrón?
2. Ejemplos comunes en JS
 - Problema y solución
3. Lecciones aprendidas

```yaml
name: Enrique Munguía
url: https://twitter.com/enrique7mc_
pic: https://pbs.twimg.com/profile_images/733322893392629760/w9u-G9Oc_400x400.jpg
bio: "Developer, instructor, learner"
```
