### ISSUE TITLE
Programación Reactiva con RxJS

### ISSUE THREAD

**Issue by enrique7mc** [eventloop/platicas#76]
### Sumario

¿Cansado de intentar construir programas asíncronos en JavaScript? 

¿Necesitas ejecutar una tarea de larga duración, mandar una petición a un servidor, iniciar una animación? 

Y además sin tener que crear un montón de _callbacks_, entra la programación reactiva al rescate.

La programación reactiva nos ofrece un enfoque diferente para resolver problemas asíncronos utilizando funciones conocidas para un programador JavaScript, que resulta en un código más simple y efectivo.

### Outline

1. Motivación de la programación reactiva
2. Introducción a RxJS
3. Operadores Comunes
4. Ejemplos de aplicación

```yaml
name: Enrique Munguía
url: https://twitter.com/enrique7mc_
pic: https://pbs.twimg.com/profile_images/733322893392629760/w9u-G9Oc_400x400.jpg
bio: "Developer, instructor, learner"
```
