### ISSUE TITLE
Desarrollo ágil de componentes de UI usando React Storybooks

### ISSUE THREAD

**Issue by Sparragus** [eventloop/platicas#77]
### Sumario
React Storybooks es un ambiente de desarrollo de componentes de UI. Con esto puedes crear una biblioteca de todos tu componentes y visualizar cada uno en un estado diferente. En pocas palabras, todos los componentes de tu aplicación, organizados en un solo sitio, listos para ser visualizados.

Porque Storybooks está integrado con webpack, tenemos de gratis _hot reloading_ durante todo el desarrollo. Con esto alcanzamos un mejor flujo de desarrollo más rápido, eficiente y de mayor calidad. 

Graciás a la fácil forma de visualizar cualquier componente, los equipos de desarrollo que usan Storybooks logran mejor comunicación con otros desarolladores, logrando mayor reuso de código; diseñadores, produciendo iteraciones más rápidas y mejores resultados; y _stakeholders_, evitando pidiendo cambios luego de semanas de trabajo.

Demo: [React Dates](http://airbnb.io/react-dates/)

### Outline
_To be decided_

### Adword

```yaml
name: Richard B. Kaufman López
url: https://twitter.com/sparragus
pic: https://pbs.twimg.com/profile_images/808770930843484160/D51oyDUA.jpg
bio: "De día hacker en aliada.mx; de noche, co-anfitrión de [Discomanía Podcast](https://twitter.com/discomania_fm)"
```

### Fecha
Eventloop de abril de 2017
