### ISSUE TITLE
Lecciones de Juego para un Robot

### ISSUE THREAD

**Issue by amaurs** [eventloop/platicas#78]
### Sumario

Inspirado en ideas de la psicología cognitiva, el *reinforcement learning* ha permitido generar algoritmos que aprenden de la experiencia cruda. Haciendo uso de estos métodos hemos logrado entrenar agentes que juegan go al nivel de los campeones mundiales, dominar videojuegos únicamente viendo las pantallas, y autos que se manejan solos. En esta plática mostraré el uso de React.js para crear ambientes en los cuales un agente interactua y aprende a resolverlos. 

[Uno de los ejemplos de juguete](https://amaurs.com/car/)

### Outline

1. Explicar el problema de un Markov Decision Process.
  - Interacción entre agente y ambiente
  - Explicación de que es una política
2. Ambientes / Agentes hechos con React.js  
  - Gridworld / Dynamic Programming
  - Car / Monte Carlo
  - Windygridworld / Temporal Difference
3. Estado del arte
  - Una rápida mención de Deep Neural Networks en javascript

### Fecha

Me gustaría darla en Mayo, o a partir de Agosto.

```yaml
name: Amaury Gutiérrez
url: https://twitter.com/amaurs
pic: https://pbs.twimg.com/profile_images/582810159065362432/E_sNdHEF_400x400.jpg
bio: Me gusta hacer cosas bonitas que no sirven para nada.
```
