### ISSUE TITLE
El futuro de React

### ISSUE THREAD

**Issue by jmz7v** [eventloop/platicas#80]
Internamente, React está siendo re-escrito desde hace más de 2 años, la meta de este cambio es hacer las cosas más fluidas a través de un nuevo proceso de renderizado.

## Outline

1. Teniendo algo de contexto sobre React
	1. Componentes de React, Elementos e Instancias 
	2. Reconciliación
	3. Scheduling
2. React Fiber
	1. Características
	2. Cambios internos
	3. Cambios externos

## Notas

Podría presentar el próximo Eventloop

Inspirado por:
Andrew Clark
What's Next for React — ReactNext 2016
https://github.com/acdlite/react-fiber-architecture
https://www.youtube.com/watch?v=aV1271hd9ew

## Acerca de

```yaml
name: Julio Montaño
url: https://jmz7v.com
pic: https://pbs.twimg.com/profile_images/822345525487812609/gQ95FYx2.jpg
bio: "Soy un desarrollador de software con interés en aprender, crear y enseñar."
```

## Adword

```
**El Futuro de React**
Por: **Julio Montaño** / @jmz7v

Internamente, React está siendo re-escrito desde hace más de 2 años, la meta de este cambio es hacer las cosas más fluidas a través de un nuevo proceso de renderizado.

> A veces aprieto CMD+Q en lugar de CMD+W por accidente.
```
