### ISSUE TITLE
Dva Framework, simplificando Redux

### ISSUE THREAD

**Issue by vansters-dev** [eventloop/platicas#81]
### Sumario

Dva.js es un **framework** que busca **simplificar la implementación de React + Redux**, está inspirado por elm. Incorpora una api reducida y una serie de conceptos que simplifican la puesta en marcha de redux. Actualmente soporta redux-sagas para controlar las operaciones asíncronas, react-native y react-router.

### Outline

1. Vistazo general del “Data Flow”.
2. Dva.js API (dva/router, dva/mobile, dva/fetch, dva/saga).
3. Dva.js Models (namespaces, reducers, effects, subscriptions).
4. Dva.js Options (plugins y triggers).
5. Ventajas de utilizar Dva.js vs implementar redux a mano.
6. Alternativas: que otros frameworks de este tipo existen.
7. Demo (Dva.js + React Native), solo demostrativo **no live coding**.

### Notas

- **El flujo de la plática es**: Tratar de recordar como es el flujo de los datos de una aplicación con los conceptos de redux, para que las personas que no lo conozcan tengan un mejor panorama de los que se va a hablar, posteriormente se va a indagar en los conceptos del framework, y mostrar la soluciones ya incluidas como el tema del router y los modelos, después hacer una comparativa entre realizar una implementación a mano de redux vs con un framework como Dva.js y para finalizar mostrar el panorama de los demás frameworks que existen.

- Puedo presentar para el evento de **Mayo**.

- Se proporcionara el demo en un repo para que mas gente pueda experimentar con Dva.js

### Sobre mí
```yaml
name: Mario Andrade
url: https://twitter.com/TheVansters
pic: https://pbs.twimg.com/profile_images/728092028018380800/pJFZwFCv.jpg
bio: "Software Engineer, Daft Punk fan"
```
