### ISSUE TITLE
Self driving tests con Nightmarejs

### ISSUE THREAD

**Issue by eduardoconekta** [eventloop/platicas#82]
### Sumario

Nightmare.js es una librería que automatiza pruebas de integración usando Electron como una mas de sus grandes propiedades para tener un _live self driving test_ (if you want), haciendolo con un pseudo lenguaje " natural " que te permite obtener cualquier componente de una interfaz por medio de diferentes notaciones (by label, by name, by css, by xpath).

Nightmare en comparación con otras librerías reduce en lo máximo el código de pruebas teniendo como premisa evitar tener demasiadas funciones anidadas por cada caso.

### Outline
1.Que son los Test

 - Tipos de test
 - Clasificación de test
 - Scope de un test
 - Flujo de testing
 - test's de Integración 
2. Que es Nightmare
 - Quien lo creo
 - Por que lo crearon
 - api (screenshots, asserts, goto, etc)
 - **nightmare** vs otros

3.  Nightmare + codecepts

 4.Test de integración  `demo` **(no live coding)** 

5. Scrapeando lo imposible + codes 

6. Que fue lo que aprendi?

```yaml
name: Eduardo Enriquez
url: https://twitter.com/Glosbe_learners
pic: https://www.linkedin.com//mpr/mpr/p/5/005/051/2f8/30731b1.jpg
bio: "Soy un estudiante de Ing. en sistemas 
apasionado con los lenguajes de programación 
me encanta aprender nuevas cosas siempre"
```
