### ISSUE TITLE
Introducción practica a la programación funcional

### ISSUE THREAD

**Issue by Emilios1995** [eventloop/platicas#83]
### Sumario

La programación funcional resuelve muchos problemas y hace que nuestro código sea claro, simple, y predecible. Sin embargo, debido a la cantidad de jargon y conceptos extraños para los no iniciados, puede ser abrumador aprender estas ideas y aplicarlas en nuestro código cotidiano. 
Para esta platica propongo dar un overview de las joyas más utiles de esta disciplina y exponer ejemplos claros y del "real world", usando las mejores librerias de JS para cada caso.

### Outline

1. Currying y composibilidad
  - Qué es, de dónde viene y porque es útil.
  - Contraejemplo: Underscore.
  - Ejemplos con Ramda.
2. Functors y Monads
  - Maybe/Either: Cómo cuidarnos de errores y valores ausentes.
     -- Sanctuary vs Ramda.
  - Lenses: El jQuery para estructuras de datos.
  - Tasks: Manejando valores del futuro.
3. Ejemplos hechos de todo lo que se habló, usando Ramda, Sanctuary y FolkTale.

### Notas

- Puedo presentar en junio
- Veo que ya tuvieron una platica sobre programación funcional. Yo no la escuché, asi que dejo a su criterio si aun hay interés en la mía.

```yaml
name: Emilio Srougo
url: https://twitter.com/emilio_srg
pic: https://pbs.twimg.com/profile_images/848368361519984640/YmM6hFWg.jpg
bio: "Obsesionado con programación funcional y otras cosas."
```
