### ISSUE TITLE
Bots & Asistentes Digitales, las nuevas Apps

### ISSUE THREAD

**Issue by kiramishima** [eventloop/platicas#85]
Primero tuvimos la web, pudimos conectar a la gente con información usando ratones y teclados. Luego llego la revolución de las aplicaciones, escritas de manera nativa o híbrida para aprovechar los sensores del dispositivo y los sistemas operativos de los dispositivos. El siguiente paso en la revolución de la información son los Bots y Asistentes Digitales, por lo que es más fácil y rápido conectar a los usuarios con la información y los servicios que necesitan y así de crear métodos que interactuen con ellos.

En esta platica hablaré sobre como el desarrollo de Bots y Asistentes Digitales ha comenzado a tomar peso en el desarrollo, y haré uso de el Microsoft Bot Framework para crear un Bots/Skills para Cortana que nos ayude a encontrar Tacos.

### Outline

1. Por que Ahora?
2. Diferencias Bot & Asistentes Digitales vs Apps
3. Conversations-as-a-Platform
4. Microsoft Bot Framework
    * Hello Eventloop
5. Agregando Inteligencia a nuestros Bots/Skill de Cortana.
    * TacoBot

```yaml
name: Paul Arizpe
url: https://twitter.com/kiramishima
pic: https://avatars3.githubusercontent.com/u/12620426?v=3&u=fb57396357b7f861d1084e1e033a5d9ffba487e5&s=400
bio: "Ing en Telecomunicaciones, ama la programación e Italia, cambia Backends hechos en Java a NodeJS/Golang/F#/Scala"
```
