### ISSUE TITLE
Caso de uso para javascript: startups

### ISSUE THREAD

**Issue by Ikana** [eventloop/platicas#87]
### Sumario

Javascript recibe mucho hate de todas las comunidades(excepto de la de php), pero después de participar en varios hackathons, code retreats, start up weekends entre otros eventos me he dado cuanta que nuestro lenguaje se presta al prototipado rápido, a fallar mucho y fallar rápido.

También últimamente existe un push de estandarización y modernización que han hecho que compañías y universidades de clase mundial se de cuenta del potencial del lenguaje.

Esta platica habla de mis experiencias trabajando con javeros, pythonistas, phperos entre otros, y poner en la mesa la ventajas (y las desventajas de javascript) para ser usado en startups.

### Outline

1. JS hoy (tc39 compliance de browsers) 
2. No tenerle miedo al fallo
3. Ventajas de un lenguaje interpretado contra uno compilado
4. Ventajas contra otros lenguajes interpretados
5. Historias de terror de uso de node a nivel masivo
6. Casos de exito de node a nivel masivo

```yaml
name: Rodrigo Quezada
url: http://roderik.io/
pic: https://pbs.twimg.com/profile_images/868613536498331652/3ab8IggO.jpg
bio: "Front-end en datank"
```
