### ISSUE TITLE
JWT: stateless authentication

### ISSUE THREAD

**Issue by memorammstein** [eventloop/platicas#89]
### Sumario

Como utilizar JWT como método y token de autenticación stateless entre Frontend y Backend, pros y cons versus sesiones con cookies, e implicaciones de seguridad.

### Outline

1. Intro a JWT
  - ¿qué es y cómo se ve un JWT?
  - ¿cómo se estructura un esquema de autenticación stateless?
2. Stateless tokens vs Stateful sessions
  - Características de implementación
  - Ventajas y desventajas
3. ¿qué tan seguro/inseguro es (o puede llegar a ser)?
  - Almacenamiento
  - Transmisión
  - encoding, hashing, encryption, and beyond
4. Pa' que amarre
  - ¿cómo comenzar a implementar JWT?
  - ¿quiénes están usando stateless auth?

### {}

```yaml
name: Guillermo Jiménez
url: http://guillermo-jimenez.xyz/
pic: https://pbs.twimg.com/profile_images/747100078842613760/0LIz6PyT_400x400.jpg
bio: "Software Engineer @ Wizeline; If it's interesting, I'm in"
```

### Notas

- `para presentar en Julio the 5th`
- busqué en los issues y no encontré que hayan dado alguna plática de esto, 
 please let me know otherwise
