### ISSUE TITLE
SQL vs NoSQL

### ISSUE THREAD

**Issue by jaimerodas** [eventloop/platicas#91]
### Sumario

El modelo de una factura a como el SAT dice, es un candidato ideal para una base de datos no relacional. En mi chamba decidimos mudar una db de cerca de 7 millones de facturas de PostgreSQL a MongoDB. Explicaré qué había, por qué no funcionaba, cómo escogimos MongoDB y cómo hicimos la migración.

### Outline

1. Qué es una factura y cómo la almacenarías en una db?
  a. Resumen del documento XML de un CFDI
  b. Cómo estaba estructurada nuestra db en SQL
  c. El problema que tenían nuestros queries
  d. La patada en los huevos que son las versiones
2. Cómo encontramos una mejor solución
  a. Bases de datos raras
  b. Bases de datos basadas en documentos
  c. Cómo llegamos a MongoDB
3. La broncota que fue crear el schema
  a. Los complementos del CFDI
  b. Estandarizando los modelos
4. Planeación de la migración
  a. Apagamos todo y prendemos después?
  b. Cómo hacerlo sin que nadie se de cuenta?
5. Ejecución de la migración
  a. Corrigiendo errores en producción
  b. Como nadie se dio cuenta de nada
6. Recap

```yaml
name: Jaime Rodas
url: https://twitter.com/scylax
pic: https://avatars3.githubusercontent.com/u/1501321
bio: "Desarrollador, administrador, y procrastinador"
```
