### ISSUE TITLE
Contribuir de regreso a mi comunidad

### ISSUE THREAD

**Issue by marulango** [eventloop/platicas#92]
### Sumario
En mis horas libres descubrí que Women Who Code tiene un programa de recompenzas por PR aceptado. Decidí usarlo como práctica y de paso, ayudar a una comunidad que me gusta mucho.

### Outline
1. Ayudando a comunidades en mi tiempo libre
  - WWCode Bounty Rewards
  - Issue #1158
  - Guidelines: En serio, RTFM
2. RubyLife cuando vienes de JS
  - ¿Qué es eso de vagrant/Virtual Box?
  - ¿Y mi PostCSS apá?
3. The Path to Merging a PR
  - Tests, porque es casa ajena
  - Aprender a trabajar sobre algo ya construido
  - Cómo contribuyo _yo_ de regreso a mi comunidad

```yaml
name: Marcela _Maru_ Lango
url: https://twitter.com/marulango
pic: https://pbs.twimg.com/profile_images/445400536569749504/8vJ-Prbe_400x400.png
bio: "Me gustan los gatitos, los tacos y Final Fantasy"
```
