### ISSUE TITLE
De ida y vuelta 

### ISSUE THREAD

**Issue by wyz3r** [eventloop/platicas#94]
### Sumario

Hablaré sobre... una aplicación realizada con sockets como tecnología se implemento de el lado de el backend node js con socket.io y en el lado de el frontend una libreria en react que ayuda a sintetizar los emits al usar sockets 

algo de lo que me di cuenta al estar estudiando WebSockets fue  como es que este protocolo es aplicable a una interacción mas humana cuando se debe de realizar la labor que todo programador tendría a mi parecer que tomar como mantra y es el resolver una necesidad a parti de nuestro trabajo  

### Outline

1. ¿El fin justifica los medios ? 
  - escuchar para entender
  - el cliente sabe lo que quiere pero no lo sabe pedir 
2. Todos somos un todo 
  - problemas con la infraestructura 
  - interfaces intuivas y capacitación 
   - tener claro que tipo de usuario sera el que use nuestra plataforma
3. demo chiquititita 

```yaml
name: Leonel Islas Gonzalez 
url: https://twitter.com/leo_ary
pic: https://avatars0.githubusercontent.com/u/15819942?v=4&u=794d8a21bfa77d657e688138756e5bdc07e6a9d5&s=400
bio: "Aprendiendo siempre un poco mas que ayer , Full-stack js en De la Riva Group "
```
