### ISSUE TITLE
Creat-react-app-ing un sideproject

### ISSUE THREAD

**Issue by mgranados** [eventloop/platicas#95]
### Summary

Hablaré sobre como utilizar creat-react-app en Agosto 2017 para crear un sideproject y lanzarlo, ventajas, desventajas, que son los serviceWorkers y que tal me fue con el lanzamiento sideproject

### Outline
0. Quien soy y asi
1. create-react-app aNewProject
  - Lo diferente que es a lo que estaba acostumbrado de proyectos previos
  - Lo que mas me gusto y facilidad para integrar cosas
  - Tener que adentrarse a 
2. El proceso de desarrollar un proyecto pequeño
  - Como ponerle backend
  - O SERVERLESS?
3. Deploy
  - Como le fue a mi proyecto
  - Unanse
  - (unanse a mis otros sideprojects)
  - PROFIT!!!!! (?????)

```yaml
name: Martin Granados 
url: https://twitter.com/mgranadosgarcia
pic: https://pbs.twimg.com/profile_images/679501416843481088/J_5a5w1L_400x400.jpg
bio: "A veces frontend, a veces backend."
```
