### ISSUE TITLE
Crea una aplicación serverless en Azure con Node.js

### ISSUE THREAD

**Issue by aminespinoza** [eventloop/platicas#96]
Las aplicaciones serverless o mejor llamadas como microservicios, proponen crear módulos con una sola tarea, permitiendo así una fragmentación de tareas enorme y la incorporación de nuevos procesos sin ningún problema para los ya existentes.

Outline:
Mi introducción.
Uso creciente de los microservicios.
Microservicios en Azure.
Despliegue de una función.
Modificar esta función usando Node.js

Amin Espinoza
Twitter: @aminespinoza

Podría presentar en cualquier edición.
```yaml
name: Amin Espinoza
url: https://twitter.com/aminespinoza
pic: https://www.facebook.com/photo.php?fbid=1329350487163995&set=a.108753045890418.12382.100002671704696&type=3&theater
bio: "Desarrollador de software, adicto a meterme solo en tantos problemas técnicos como sea posible".
```
