### ISSUE TITLE
Automatización de procesos y tareas con proyectos NODE

### ISSUE THREAD

**Issue by yacafx** [eventloop/platicas#97]
Diariamente realizamos una enorme cantidad de tareas y procesos que nos quitan mucho tiempo valioso que podríamos aprovechar escribiendo buen código. En esta charla aprenderas a darle orden a tu proceso de desarrollo automatizando tareas y ahorrando mucho tiempo al evitar perder tiempo como en el a veces eterno *npm install*

**Outline** 

* ¿Quien soy y que hago?
* Ordenando tu proyecto
* Identificando tareas y procesos
* Seleccion de servidores Node
* Uso de Buddy Works
* Despliege de tu proyecto
* Ejecución automática de comandos 
* Uso de notificaciones
* Q&A

Puedo presentar cualquier edición ;)

```yaml
name: Sergio Brito
url: https://twitter.com/yacafx | https://www.linkedin.com/learning/instructors/sergio-brito
pic: https://goo.gl/PRQpuY
bio: Web developer en Roswell MX, consultor e instructor en LinkedIn/Lynda.com. Fanático de los 49ers
```
