### ISSUE TITLE
Server Side React

### ISSUE THREAD

**Issue by xalakox** [eventloop/platicas#98]
### Sumario

Uso de React para templating en Express y ...
Rendering de Server Side para SEO

Idealmente: Octubre.

### Outline

1. ¿ Por que ?
2.  React como templating engine
3.  SEO con Sever Side Rendering

```yaml
name: Salvador Aceves
url: http://salvador.aceves.mx
pic: https://aboutme.imgix.net/background/users/s/a/l/salvadoraceves_1498086082_393.jpg
bio: "Dev, tratando de hacerse mainstream."
```
